# Generated by Django 2.1.2 on 2019-01-29 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('courseid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='student')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('mob_number', models.CharField(default=' ', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='student')),
                ('roll_no', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('webmail', models.CharField(max_length=128, unique=True)),
                ('degree', models.CharField(blank=True, choices=[('Mtech', 'Mtech'), ('Phd', 'Phd'), ('Btech', 'Btech')], max_length=128)),
                ('acedemic_year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0)),
                ('present_semester', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], null=True)),
                ('hostel_name', models.CharField(blank=True, choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('Married_Scholar', 'Married_Scholar')], default='', max_length=255)),
                ('mob_number', models.CharField(default=' ', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='uploads/')),
                ('type', models.CharField(choices=[('Midsem', 'Midsem'), ('Endsem', 'Endsem'), ('Quiz', 'Quiz'), ('Book', 'Book'), ('Slide', 'Slide'), ('Miscalleneous', 'Miscalleneous')], max_length=35)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.Course')),
            ],
        ),
    ]
